### PR TITLE
'rec' replacement with snowboy

### PR DESCRIPTION
**Pull request by guillaumef**
Same player again...

This pull is for you to test and perhaps consider, because it could impact lots of your users.
With the snowboy hot-word perfectly working now, i had some problem with 'rec' detecting wrongly the end of the sentence... and failing with bing speech since the sentence was not complete.
I shake the configuration of 'rec' with the silence pattern in every way without a lot of success, sometimes working, sometimes not. It was triggering the end without validating the given silence constraint and most of the time cutting the start of my sentence.
Since snowboy was perfectly working to detect silence, I wrote a replacement of 'rec' with snowboy and the same pattern mechanism.
This time, it is only Silence - Voice - Silence.
It works great (for me)

It has a lot of impact since, with this recorder, 5 configuration variables become useless (noise/silence) in Config>Audio.
'Gain' is still useful to increase the gain only for the command recognition.
The "Auto-adjust levels" and Volume and Sensitivity are still useful to calibrate the mic.

But it makes Jarvis "snowboy dependent". Perhaps it is a problem, but since the recommended hot-word detector is snowboy, i don't know.
In fact, it is also possible to manage both recorder.
Adding the ticks pattern configuration for snowboy hot-word and a snowboy recorder could be also quite nice since it could simplify and unify the concept.
I had to concentrate to understand the Min/Max noise/silence stuff in Config>Audio ;-) I got it after reading the 'rec' manpage.

I think it is my last modification with Jarvis. Now, everything is working great with bing (the power of Jarvis is unleashed in my home)
Bonne nuit!

### CODE REVIEW

**Comment by alexylem** [comment]
Thanks a lot @guillaumef for the time you spent on this and for the detailed explanation.
I have read it this morning and though about it throughout the day.
It is indeed a great evolution, and it seems to fix the issue with sox that is "cutting" the beginning and end of our sentences in some cases.
For the dependency, it is not too much  a pb as you say Jarvis already recommends snowboy for the hotword recognition. However there are platforms where snowboy needs to be compiled (some Ubuntu/Debians/others), and as snowboy is not mandatory to use Jarvis there should be another option proposed.
I will therefore propose the two recoders (as you suggested), but recommend Snowboy if the package is available. Sox otherwize. Sorry that you had to open the rec manpage. I tried to explicitely name the silence arguments, but that part is not well documented (actually it is the first part of Jarvis that I wrote, and almost never touched it since).
I will take the time to test the performance impact of this: python snowboy is slower to load than sox, and I saw in the code there is a conversion from raw to wav. Bing is already slow to translate, and I want to make sure this doesn't add too much time.
And finally I will of course review various audio settings, and make the ticks available in the user configuration.
These two contributions that you did is making Jarvis reach a new level, especially regarding the "competition". Merci infiniement!!

**Comment by guillaumef** [comment]
Hi @alexylem 

Thank you a lot to consider all theses changes. It's nice.

Some goodies i added here:
- limit the snowboy_STT in trigger mode to the model specified. It avoids snowboy stop/start if another model (other than the trigger one) is detected and rejected in the 'main.sh'. When having multiple pmdl files, during my test, i saw successive snowboy triggering of 2 models in 2 ticks voice distance... which is quite awkward. By limiting the number of possible model, this behavior is cancelled.
  (in reverse, if snowboy is used in command mode, the trigger model should be avoid, i didn't implement this one - it is just a 'else' to apply on the diff produced on the file 'main.sh' - the model preload block)
- a track mode in wavget, to watch the live Voice/Silence pattern. Nice to tune the gain and get a feeling of the ticks frequency. 'python -d stt_engines/snowboy/mainwav.py \<gain\> track'
```
WARNING:jarvis:     1 Silence
WARNING:jarvis:     2 Silence
WARNING:jarvis:     3 Silence
WARNING:jarvis:     4 Voice
WARNING:jarvis:     5 Voice
 ....
```

I follow you on snowboy loading time, it's the cost of python.
On my htpc, it takes 300ms from the command run to the first tick from snowboy.
It seems high on paper but i don't really feel it.
Perhaps some things, like the "play" command saying "Yes?" after the trigger validation, could be send to background to let bash continue its treatment and activate faster the recorder.

For the raw to wav conversion, it is insignificant. 2ms on my gear.
The python system call is perhaps more costly than the sox conversion itself ;-)

I'm running the stuff on a Nuc i3, max freq at 700Mhz. But it is surely faster than the Pi3.
With the usb Andoer Mic, the one listed on Jarvis website, i get now a clean STT at 5 meters, speaking normally, not any false positive even with a movie playing or the hi-fi.
No need to disable jarvis when it's noisy (i was considering the option before the python work).

I thought to a feature (during the work on main.sh) which could be nice also with minimal work: manage multiple 'trigger' pmdl files and not only one.
pmdl's problem is the resulting model is bind to one specific voice.
It could allow to lower the snowboy sensitivity configuration and register multiple users to trigger the command mode.

Bye!

**Comment by guillaumef** [comment]
Hi @alexylem ,

Quick commands, I don't know and didn't check this one.
You have to be really cautious with what i wrote here. I don't know the internals of jarvis and I'm a total newbie on it (5 days).

And of course, there is no hurry at all.
I have rush a bit on Jarvis myself because i'm a bit compulsive... and I prefer to fill the pull request with info i could probably forget later. My Jarvis git tree is already a mess of code ;-)
Sorry if you took it like an urge.

Trigger me if you need anything and if I'm popping with something else, I let you know with a better packaging.
Bonne soirée.

**Comment by Smanar** [comment]
If you don't use compression, RAW and WAV format is exactly the same thing, you just need to create a header file for WAV and copy all the RAW file just after. if your file is already loaded you can make it in python, faster than load an other application.

**Comment by alexylem** [comment]
The recording improvement is impressive!
But quite a lot of work to all integrate properly 😄  
Working on it, hope I will finished this weekend

**Comment by alexylem** [comment]
I have merged it and for now it is quite hidden (before I test it on the long run in my production Jarvis).
To enable the "snowboy" recorder, select it in Settings > Audio > Recorder (by default everyone has "sox")
I have done some few tweaks for the display.

**Comment by guillaumef** [comment]
Great!
I'm doing for the modification suggested by @Smanar . Thanks!
If it can save one system call, it is cool. I also already made the data buffering a different way, in memory, to speed up the process and avoid making a write for each snowboy packet.
I add it here when its done.

**Comment by alexylem** [comment]
This PR is merged, create a new one 😄 
Please update your version of Jarvis before, I have moved some of your files in the new `recorders/snowboy` folder.
Some other key files have changed / moved.

**Pull request merged**
